@startuml
title yarnでイラストを動かす コールチェーン

box "Unity" #LightBlue
	participant YarnScenarioStarter
	participant ScenarioSpriteSwitcher
end box
box "スプライト切り替え機能" #LightPink
	participant ISpriteLayerController
	participant スプライト切り替え機能
end box

ScenarioSpriteSwitcher -> ISpriteLayerController : スプライト切り替え指示
ISpriteLayerController -> スプライト切り替え機能 : 以降は既存のイラスト差し替え機能のコールチェーン
@enduml